version: "3.8"

services:
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  discovery-service:
    build:
      context: ./discovery-service
    container_name: discovery-service-app
    ports:
      - "8761:8761"
    networks:
      - backend

  user-service:
    build:
      context: ./user-service
    container_name: user-service-app
    ports:
      - "8001:8001"
    depends_on:
      - discovery-service
      - redis
    networks:
      - backend

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service-app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8000:8000"
    depends_on:
      - discovery-service
      - user-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
